run:
    skip-dirs:
        - plugin/example
        - plugin/testing

linters:
    enable:
        - asciicheck
        - deadcode
        - depguard
        - exportloopref
        - gci
        - godot
        - gofmt
        - gofumpt
        - goimports
        - revive
        - gomodguard
        - goprintffuncname
        - gosimple
        - govet
        - misspell
        - nakedret
        - nolintlint
        - sqlclosecheck
        - staticcheck
        - structcheck
        - typecheck
        - unconvert
        - unused
        - varcheck
        - whitespace
    disable:
        - goerr113
        - errcheck
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - gocyclo
        - godox
        - gomnd
        - lll
        - maligned
        - nestif
        - nlreturn
        - noctx
        - testpackage
        - wsl
        - ineffassign
        - interfacer

linters-settings:
    gofumpt:
        extra-rules: true
    misspell:
        locale: US
