issues:
    exclude-dirs:
        - example

linters:
    enable:
        - asciicheck
        - gci
        - godot
        - gofmt
        - gofumpt
        - goimports
        - gomodguard
        - goprintffuncname
        - gosimple
        - govet
        - misspell
        - nakedret
        - nolintlint
        - sqlclosecheck
        - typecheck
        - unconvert
        - unused
        - whitespace
    disable:
        - errcheck
        - revive
        - funlen
        - gochecknoglobals
        - staticcheck
        - gocognit
        - goconst
        - gocyclo
        - godox
        - lll
        - nestif
        - nlreturn
        - noctx
        - testpackage
        - wsl
        - ineffassign

linters-settings:
    gofumpt:
        extra-rules: true
    misspell:
        locale: US
