// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package a

type CIntoAImpl struct{}

func (c *CIntoAImpl) Convert(source []int) []int {
	var intList []int
	if source != nil {
		intList = make([]int, len(source))
		for i := 0; i < len(source); i++ {
			intList[i] = source[i]
		}
	}
	return intList
}

type RootAImpl struct{}

func (c *RootAImpl) Convert(source []bool) []bool {
	var boolList []bool
	if source != nil {
		boolList = make([]bool, len(source))
		for i := 0; i < len(source); i++ {
			boolList[i] = source[i]
		}
	}
	return boolList
}
