// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package samepackage

type ConverterImpl struct{}

func (c *ConverterImpl) Convert(source *Input) *Output {
	var pSamepackageOutput *Output
	if source != nil {
		var samepackageOutput Output
		samepackageOutput.Name = (*source).Name
		pSamepackageOutput = &samepackageOutput
	}
	return pSamepackageOutput
}
