// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package package_name_that_doesnt_match_dir_name

type ConverterImpl struct{}

func (c *ConverterImpl) Convert(source *Input) *Output {
	var pPackage_name_that_doesnt_match_dir_nameOutput *Output
	if source != nil {
		var package_name_that_doesnt_match_dir_nameOutput Output
		package_name_that_doesnt_match_dir_nameOutput.Name = (*source).Name
		pPackage_name_that_doesnt_match_dir_nameOutput = &package_name_that_doesnt_match_dir_nameOutput
	}
	return pPackage_name_that_doesnt_match_dir_nameOutput
}
